2019-11-03 17:04:36,728 ERROR: Exception on /edit/article [GET] [in /home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/anonymous/sites/flask_mega/app/routes.py", line 108, in edit_article
    return render_template("edit_article.html", title="Edit Article", form=form)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/anonymous/sites/flask_mega/app/templates/edit_article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/anonymous/sites/flask_mega/app/templates/edit_article.html", line 14, in root
    {% for error in form.username.errors %}
  File "/home/anonymous/sites/flask_mega/app/templates/base.html", line 58, in root
  File "/home/anonymous/sites/flask_mega/app/templates/edit_article.html", line 28, in block_content
    <div class="article sticky-edit">
  File "/home/anonymous/sites/flask_mega/env/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.EditArticleForm object' has no attribute 'username'
2019-11-03 17:07:56,184 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 17:08:06,203 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 17:09:44,558 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 20:15:13,646 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 20:20:03,945 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 20:22:40,856 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 20:24:02,159 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 20:26:00,359 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-03 20:46:14,976 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-04 21:27:53,301 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
2019-11-04 21:31:45,341 INFO: Ochyro startup [in /home/anonymous/sites/flask_mega/app/__init__.py:30
